project:
  type: website
  output-dir: docs

website:
  title: "APS 2024 Workshop: Reproducible Manuscripts in R"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: slides/workshop-materials.qmd
        text: Workshop Materials
      - href: slides/introduction.qmd
        text: Introduction
      - href: slides/getting-started.qmd
        text: Getting Started
      - href: slides/markdown-syntax.qmd
        text: Writing/References
      - href: slides/code-chunks.qmd
        text: Analysis
      - href: slides/rendering.qmd
        text: Rendering

format:
  html:
    theme: superhero
    css: styles.css
    toc: true
    fontsize: "18pt"

editor: visual

